name: ci_pull

on:
  pull_request:
    paths:
      - '!**.md'
    branches:
      - master

jobs:
  build_macos:
    steps:
      - name: Tap custom repository
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/${GITHUB_REPOSITORY}"
          mkdir -p "${HOMEBREW_TAP_DIR}"
          rm -rf "{$HOMEBREW_TAP_DIR}"
          ln -s "${PWD}" "${HOMEBREW_TAP_DIR}"
      - name: Run brew test-bot
        if: success()
        shell: bash
        run: |
          set -ex
          echo "GIT-URL:   https://www.github.com${GITHUB_REPOSITORY}"
          echo "COMMIT-ID: ${GITHUB_SHA}"
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/${GITHUB_REPOSITORY}"
          brew test-bot
          ls *.bottle.json || echo "==> No bottle created here"
        env:
          HOMEBREW_GITHUB_USER: ${{ secrets.GITHUB_USER }}
          HOMEBREW_GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          HOMEBREW_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    name: "CI: macOS pull request"
    runs-on: [macos-latest]
